services:
  - type: web
    name: sistema-academico
    env: python
    buildCommand: "pip install -r requirements.txt && cd sistema_academico && python manage.py collectstatic --noinput"
    startCommand: "cd sistema_academico && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: sga-db
          property: connectionString
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: sga-db
    databaseName: sga
    user: sga_user
